services:
  server:
    build:
      context: ..
      dockerfile: infra/server.Dockerfile
    restart: unless-stopped
    env_file:
      - ../server/.env
    volumes:
      - ../server/data:/app/data
    ports:
      - "4000:4000"

  client:
    build:
      context: ..
      dockerfile: infra/client.Dockerfile
    restart: unless-stopped
    environment:
      SERVER_URL: http://server:4000
    depends_on:
      - server
    ports:
      - "8443:3000"
